/*
  KPEE 필라테스 교재(Barrel / Cadillac / Chair / Mat / Reformer) 목차를 바탕으로 만든 동작 데이터베이스.
  - 출처: 각 교재 표지 뒤 목차(Table of Contents) + 강사(동생분)의 손글씨 주석
  - spring: 손글씨로 명확히 단일 항목에 붙어있던 스프링 세팅만 반영 (애매하게 여러 항목을 묶은 표기는 비워둠 → 직접 채워주세요)
  - excluded: 손글씨로 X 표시되어 "안 쓰는 동작"으로 명확히 표시된 것만 true
  - level: 목차만으로는 난이도가 구분되지 않아 기본값 "all". 본문 상세 페이지를 더 읽으면 정교화 가능
  - page: 교재 내 페이지 번호 (강사가 원본 교재에서 다시 찾아볼 때 참고용)
  주의: 손글씨 인식은 100% 정확하지 않을 수 있습니다. 앱의 "동작 편집"에서 언제든 수정하세요.
*/

const EXERCISE_DB = {
  barrel: {
    label: "래더 바렐 (Ladder Barrel)",
    items: [
      { name: "Hamstring Stretch", category: "Ladder Barrel Stretches", page: 3, variations: [] },
      { name: "Hip External Rotator Stretch", category: "Ladder Barrel Stretches", page: 4, variations: [] },
      { name: "Hip Adductor Stretch", category: "Ladder Barrel Stretches", page: 5, variations: [] },
      { name: "Hip Flexor Stretch", category: "Ladder Barrel Stretches", page: 6, variations: [] },
      { name: "Quadriceps Stretch", category: "Ladder Barrel Stretches", page: 7, variations: [] },
      { name: "Hip Abductor Stretch & Trunk Lateral Flexor Stretch", category: "Ladder Barrel Stretches", page: 8, variations: [] },
      { name: "Side Bend", category: "Side Bend", page: 11, variations: ["Side Bend with Rotation", "Rotation with Flexion & Extension"] },
      { name: "Prone Extension", category: "Prone Extension", page: 15, variations: [] },
      { name: "Swan Dive 1", category: "Swan Dive", page: 17, variations: [] },
      { name: "Rotation Prone", category: "Rotation Prone", page: 22, variations: [] },
      { name: "Roll Down (Roll Back)", category: "Roll Down", page: 24, variations: ["Round Back Roll Down", "Oblique Abdominals", "Flat Back Roll Down"] },
      { name: "Climb a Tree", category: "Climb a Tree", page: 29, variations: [], excluded: true },
      { name: "Bridge on Ladder Barrel", category: "Bridge", page: 35, variations: [] },
      { name: "Sit Up on Barrel", category: "Sit Up", page: 37, variations: ["Scissors", "Bicycle", "Lower & Lift", "Legs Circle", "Hip Circles (Hip Twist)"] },
      { name: "Horseback", category: "Horseback", page: 43, variations: [] },
      { name: "Prone on Barrel", category: "Prone on Barrel", page: 46, variations: ["Lower & Lift", "Leg Circles", "Scissors", "Beats"] },
      { name: "Swan Dive 2", category: "Swan Dive", page: 49, variations: [] },
      { name: "Side Lying on Barrel", category: "Side Lying", page: 51, variations: ["Single Leg Lift", "Lower Leg Lift", "Double Leg Lift", "Scissors", "One Arm Press"] }
    ]
  },
  cadillac: {
    label: "캐딜락 (Cadillac)",
    items: [
      { name: "Forward Push Through (Flat/Round Back)", category: "Push Through Bar - Sitting", page: 7, variations: [] },
      { name: "Circle with Push Through Bar (Circle Saw)", category: "Push Through Bar - Sitting", page: 11, variations: [] },
      { name: "Cat Stretch", category: "Push Through Bar - Sitting", page: 16, variations: [] },
      { name: "Scapular Glides", category: "Push Through Bar - Sitting", page: 24, variations: [] },
      { name: "Lat. Pull (Pull Downs)", category: "Push Through Bar - Sitting", page: 26, variations: ["Single", "Double"] },
      { name: "Mermaid", category: "Push Through Bar - Sitting", page: 29, variations: [] },
      { name: "AB. Curl Up", category: "분절 및 복부 강화", page: 38, variations: [] },
      { name: "Upper Arms", category: "분절 및 복부 강화", page: 40, variations: [] },
      { name: "Assisted Sit Ups", category: "분절 및 복부 강화", page: 42, variations: [] },
      { name: "Advanced Sit Ups", category: "분절 및 복부 강화", page: 45, variations: [] },
      { name: "Breathing Push Through Bar", category: "분절 및 복부 강화", page: 48, variations: [] },
      { name: "Teaser 1,2,3,4", category: "분절 및 복부 강화", page: 51, variations: [] },
      { name: "Push Through Back", category: "분절 및 복부 강화", page: 56, variations: [] },
      { name: "Parakeet", category: "분절 및 복부 강화", page: 59, variations: [] },
      { name: "Water Ski (Bridging)", category: "분절 및 복부 강화", page: 66, variations: [] },
      { name: "Swan with push through bar", category: "후면 강화", page: 70, variations: [] },
      { name: "Advanced Swan with push through bar", category: "후면 강화", page: 72, variations: [] },
      { name: "Foot Work series", category: "Lower Spring", page: 75, variations: ["Bend and Stretch (Leg Press)", "Heel Up & Down", "Running in Place"] },
      { name: "Hamstring Stretch", category: "Lower Spring", page: 78, variations: [] },
      { name: "Monkey", category: "Lower Spring", page: 80, variations: [] },
      { name: "Tower", category: "Lower Spring", page: 82, variations: [] },
      { name: "Hip Extension", category: "Lower Spring", page: 84, variations: [] },
      { name: "Abduction & Adduction", category: "Lower Spring", page: 86, variations: [] },
      { name: "Roll Down", category: "Roll Down Bar", page: 88, variations: ["Round Back Roll Down", "Roll Down with Biceps Curls", "Roll Down with Rowing", "Roll Down with Oblique", "Water Skier with Roll Down Bar", "Flat Back Roll Down", "Arch and Curl"] },
      { name: "Side Bends", category: "Roll Down Bar", page: 97, variations: [] },
      { name: "The Hundred", category: "Roll Down Bar", page: 99, variations: [] },
      { name: "Breathing Roll Down Bar", category: "Roll Down Bar", page: 100, variations: [] },
      { name: "Short Spine with roll down bar", category: "Roll Down Bar", page: 102, variations: [] },
      { name: "Swan with roll down bar", category: "Roll Down Bar", page: 105, variations: [] },
      { name: "Chest Expansion", category: "Roll Down Bar", page: 107, variations: [] },
      { name: "Thigh Stretch", category: "Roll Down Bar", page: 109, variations: [] },
      { name: "Rolling In and Out", category: "Roll Down Bar", page: 112, variations: [] }
    ]
  },
  chair: {
    label: "체어 (Chair)",
    items: [
      { name: "Cat Standing Front", category: "Cat Standing", page: 5, variations: ["Abdominal Pulses", "Knee Bend & Stretch (Hamstring Stretch)", "Articulation"] },
      { name: "Cat Standing Back", category: "Cat Standing", page: 9, variations: ["Abdominal Pulses", "Articulation"] },
      { name: "Cat Kneeling", category: "Cat Standing", page: 13, variations: ["Abdominal Pulses", "Articulation"] },
      { name: "Standing Roll Down Twist", category: "Standing", page: 17, variations: [] },
      { name: "Leg Pumps", category: "Standing", page: 20, spring: "2H1/2H2", variations: ["Double Leg Pumps", "Single Leg Pumps"] },
      { name: "Standing Leg Press Front", category: "Standing", page: 23, spring: "2H2", variations: [] },
      { name: "Standing Leg Press Side", category: "Standing", page: 25, spring: "2H2", variations: [] },
      { name: "Achilles Stretch", category: "Standing", page: 27, spring: "2H1", variations: [] },
      { name: "Pull Pike (Pull Up)", category: "Standing", page: 29, spring: "2H3/2H4", variations: ["Pull Pike Oblique (Pull Up Oblique)"] },
      { name: "Frog Standing", category: "Standing", page: 34, variations: ["Frog Front", "Frog Back", "Frog Back Hip Up"] },
      { name: "Tendon Stretch", category: "Standing", page: 40, spring: "2H3/2H4", variations: [] },
      { name: "Front Lunge", category: "Lunge", page: 43, spring: "2H3", variations: ["Front Lunge – Intermediate", "Full Front Lunge – Advanced"] },
      { name: "Side Lunge", category: "Lunge", page: 46, spring: "2H2", variations: ["Side Lunge – Intermediate", "Full Side Lunge – Advanced"] },
      { name: "Step Downs", category: "Lunge", page: 49, variations: ["Backward – Running Start", "Sideways – Side Russian", "Forward – Russian"], excluded: true },
      { name: "Dips 1. Facing the Chair", category: "Dips", page: 53, variations: [], excluded: true },
      { name: "Dips 2. Facing away from the Chair", category: "Dips", page: 58, variations: [] },
      { name: "Triceps Press Down", category: "Standing", page: 62, spring: "2L1", variations: [] },
      { name: "Plie Front and Back", category: "Standing", page: 64, variations: ["Plie Front", "Plie Back"], excluded: true },
      { name: "Supine Double Leg Pump", category: "Supine", page: 69, variations: ["Hamstring Curls", "Bridging", "Bridging Marching", "Isometric Bridging", "Moving Bridging", "Shoulder Bridging"] },
      { name: "Scapular Mobilization", category: "Sitting - Upper Body", page: 75, spring: "2L2", variations: ["Double Arm", "Single Arm", "Alternating Single Arm", "Alternating With Twist", "Around the World"] },
      { name: "Chest Press", category: "Sitting - Upper Body", page: 80, spring: "2L2", variations: ["Chest Press – Triceps", "Chest Press – Pectoralis"] },
      { name: "Swan on Seat", category: "Swan", page: 82, spring: "2L4", variations: [] },
      { name: "Swan on the Floor", category: "Swan", page: 84, spring: "2L1", variations: [] },
      { name: "Seated Mermaid", category: "Mermaid", page: 86, spring: "2L2/2L3", variations: ["Both Legs in Front", "One Leg to the Side"] },
      { name: "Kneeling Mermaid", category: "Mermaid", page: 90, spring: "2L1", variations: [] },
      { name: "Side Lying on the Chair", category: "Side Lying", page: 94, spring: "2L1", variations: ["Side Lying Oblique", "Side Body Twist"] },
      { name: "Spine Stretch", category: "Sitting", page: 97, variations: [], excluded: true },
      { name: "Teaser on Floor", category: "Floor", page: 100, spring: "1H2", variations: [] },
      { name: "Reverse Swan", category: "Floor", page: 102, variations: ["Torso Press Sit (2H1)", "Torso Press Sit with Leg Raise", "Side Arm Twist (2L3)"] },
      { name: "Jackknife", category: "Floor", page: 108, variations: [], excluded: true },
      { name: "One Arm Push-Ups", category: "Floor", page: 111, variations: ["One hand on the Floor, One hand on the Pedal", "Both hands on the Pedal"], excluded: true },
      { name: "Handstand", category: "Advanced", page: 116, variations: ["Pikes", "Handstand Plank"], excluded: true }
    ]
  },
  reformer: {
    label: "리포머 (Reformer)",
    items: [
      { name: "Footwork Series - Double", category: "Footwork", page: 12, variations: ["Leg Press", "Heel Up & Down", "Running"] },
      { name: "Footwork Series - Single", category: "Footwork", page: 15, variations: ["Single Leg Press", "Diagonal Leg", "Bend & Reach", "Coordination - Parallel", "Coordination - V-feet"] },
      { name: "Footwork on Footplate", category: "Footwork", page: 23, variations: ["Leg Press"] },
      { name: "Jumping on Footplate", category: "Jumping", page: 24, variations: ["Running in Place", "Jumping", "Jumping - Single Leg"] },
      { name: "Bridging & Pelvic Lift", category: "Bridging", page: 27, variations: ["Bridging (Prep.)", "Pelvic Lift", "Single Leg Pelvic Lift"] },
      { name: "Semi Circle", category: "Bridging", page: 30, variations: [] },
      { name: "Long Bridge", category: "Bridging", page: 33, variations: [], excluded: true },
      { name: "High Bridge - Hands on Foot Bar", category: "Bridging", page: 36, variations: [], excluded: true },
      { name: "Stomach Massage", category: "Stomach Massage", page: 38, variations: ["Prep.", "Round Back", "Flat Back"] },
      { name: "Supine Arm Work", category: "Supine Arm Work", page: 43, variations: ["Posterior Deltoid Pull", "Triceps Pull", "Latissimus Dorsi Pull", "Arm Circles"] },
      { name: "The Hundred", category: "Supine Abdominals", page: 47, variations: [] },
      { name: "Coordination", category: "Supine Abdominals", page: 49, variations: [] },
      { name: "Jackknife", category: "Supine Abdominals", page: 51, variations: [] },
      { name: "Feet in Straps", category: "Feet in Straps", page: 54, variations: ["Up & Down", "Scissors", "Circles", "Bend & Reach"] },
      { name: "Long Spine", category: "Feet in Straps", page: 59, variations: [] },
      { name: "Short Spine", category: "Feet in Straps", page: 61, variations: [] },
      { name: "Roll Down with Arm Work", category: "Roll Down", page: 63, variations: ["Roll Down", "Oblique", "Biceps Curl", "Open the Arms", "Posterior Shoulder Press", "Triceps Curl", "Rowing", "Double Arm Twist"] },
      { name: "Arm Work - Facing Straps", category: "Arm Work", page: 69, variations: ["Biceps Curl", "Posterior Shoulder Press", "Triceps Curl", "Open the Arms", "Rowing", "External Rotation", "Double Arm Twist"] },
      { name: "Arm Work - Facing Foot Bar", category: "Arm Work", page: 74, variations: ["Elbow Extension & Flexion", "Serve a Tray", "Hug a Tree", "Salutes", "Twist Front (Punching)"] },
      { name: "Arm Work - Facing Side", category: "Arm Work", page: 80, variations: ["Internal Rotation", "External Rotation", "Abduction", "Adduction", "Sitting Side Twist", "Over Head Press", "High O"] },
      { name: "Rowing Front", category: "Rowing", page: 85, variations: ["Sitting Tall", "Bending Down"] },
      { name: "Rowing Back", category: "Rowing", page: 90, variations: ["Round Back", "Flat Back"] },
      { name: "Chest Expansion", category: "Upper Body", page: 97, variations: [] },
      { name: "Thigh Stretch", category: "Kneeling", page: 100, variations: [] },
      { name: "Kneeling Abdominals - Facing Back", category: "Kneeling Abdominals", page: 103, variations: ["Flat Back", "Round Back", "Oblique"] },
      { name: "Kneeling Abdominals - Facing Front", category: "Kneeling Abdominals", page: 106, variations: [] },
      { name: "Hip Flexor Stretch", category: "Stretch", page: 108, variations: [] },
      { name: "Lunge", category: "Lunge", page: 109, variations: [] },
      { name: "Single Leg Knee Stretch", category: "Knee Stretch", page: 110, variations: [] },
      { name: "Knee Stretch", category: "Knee Stretch", page: 112, variations: ["Flat Back", "Round Back"] },
      { name: "Knee Stretch - Knees Off", category: "Knee Stretch", page: 114, variations: ["Flat Back", "Round Back"] },
      { name: "Down Stretch", category: "Long Stretch Series", page: 117, variations: [] },
      { name: "Elephant", category: "Long Stretch Series", page: 119, variations: ["Flat Back", "Round Back", "Walking"] },
      { name: "Long Stretch", category: "Long Stretch Series", page: 124, variations: ["Flat Back", "Round Back", "Arched Back"] },
      { name: "Up Stretch", category: "Long Stretch Series", page: 127, variations: ["Flat Back", "Flat Back - Reverse"] },
      { name: "Arabesque & Single Leg Elephant", category: "Long Stretch Series", page: 130, variations: [] },
      { name: "Abdominals Works on a Short Box", category: "Short Box", page: 134, variations: ["Round Back Roll Down", "Flat Back Roll Down", "Twist", "Spear a Fish", "Around the World", "Advanced Abdominals", "Climb a Tree"] },
      { name: "Side Bend Series on a Short Box", category: "Short Box", page: 151, variations: ["Mermaid", "Side Sit Up", "Side Bend Coordination"] },
      { name: "Arm Works on a Long Box - Facing Strap", category: "Long Box", page: 156, variations: ["Pulling Downs", "Pulling in a T", "Pulling Triceps", "Pulling Strap"] },
      { name: "Arm Works on a Long Box - Facing Foot Bar", category: "Long Box", page: 160, variations: ["Overhead Press", "Swan with Foot Bar"] },
      { name: "Swan Dive & Grasshopper on a Long Box", category: "Long Box", page: 163, variations: [], excluded: true },
      { name: "Advanced Swan on a Long Box", category: "Long Box", page: 166, variations: [] },
      { name: "Swimming on a Long Box", category: "Long Box", page: 168, variations: [] },
      { name: "Arm Works on a Long Box - Breast Stroke", category: "Long Box", page: 170, variations: [] },
      { name: "Feet Pulling Straps on a Long Box - Facing Foot Bar", category: "Long Box", page: 173, variations: ["Hamstring Curls", "Feet Pulling Straps", "Double Leg Kick"] },
      { name: "Rocking", category: "Long Box", page: 179, variations: [], excluded: true },
      { name: "Feet Pulling Straps on a Long Box - Facing Strap", category: "Long Box", page: 181, variations: ["Kneeling One Pull", "Side Lying One Leg Pull", "Knee Lift (Clams)"], excluded: true },
      { name: "Abdominals Works on a Long Box", category: "Long Box", page: 187, variations: ["Back Stroke", "Teaser on the Box"] },
      { name: "Side Stretch (Mermaid)", category: "Side Stretch", page: 194, variations: [] },
      { name: "Cleopatra", category: "Side Stretch", page: 199, variations: [] },
      { name: "Star Prep", category: "Side Body", page: 201, variations: [] },
      { name: "Star Series", category: "Side Body", page: 202, variations: ["Star Elephant", "Star", "Star Side Kick"], excluded: true },
      { name: "Side Splits", category: "Splits", page: 207, variations: ["Abduction", "Adduction", "Plie Out", "Plie In", "Carriage Leg Pressing", "Platform Leg Pressing", "Cross Touch"] },
      { name: "Front Splits", category: "Splits", page: 214, variations: [] },
      { name: "Back Splits", category: "Splits", page: 216, variations: [] },
      { name: "Control Front", category: "Control", page: 219, variations: ["Straight Arms", "Bent Arms Out", "Bent Arms In"] },
      { name: "Control Back", category: "Control", page: 224, variations: [], excluded: true },
      { name: "Tendon Stretch", category: "Advanced", page: 227, variations: [], excluded: true },
      { name: "Long Back Stretch (Slide)", category: "Advanced", page: 229, variations: [], excluded: true },
      { name: "Snake", category: "Advanced", page: 232, variations: [], excluded: true },
      { name: "Snake with Twist", category: "Advanced", page: 234, variations: [], excluded: true }
    ]
  },
  mat: {
    label: "매트 (Mat)",
    items: [
      { name: "Neck Control", category: "Supine", page: 6, variations: ["Nose Nods", "Head Roll", "Nose Circles"] },
      { name: "Hip joint Control", category: "Supine", page: 8, variations: ["Lifted Frog", "Double Knee Circles"] },
      { name: "Hip joint Muscle release", category: "Supine", page: 9, variations: ["Hip Flexor Stretch", "Buttock Stretch", "Hamstring Stretch", "Bridge Side to Side"] },
      { name: "Pelvic Clock", category: "Supine", page: 11, variations: [] },
      { name: "하지의 움직임을 이용한 코어 인지", category: "Supine", page: 13, variations: ["Single Leg Slide", "Single Knee Float (Marching)", "Toe Tap", "Up Up Down Down", "One Leg Circle"] },
      { name: "상지의 움직임을 통한 코어 인지", category: "Supine", page: 19, variations: ["Arm Float", "Shoulder Shrug", "Arm Over Head", "Alternate Arms", "Arm Open", "Angel Arms"] },
      { name: "상,하지의 움직임을 통한 코어 인지", category: "Supine", page: 22, variations: ["Alternate Arm and Leg Slide", "Dead Bug"] },
      { name: "Bridge", category: "Supine", page: 24, variations: [] },
      { name: "Bridge Marching", category: "Supine", page: 27, variations: [] },
      { name: "Shoulder Bridge", category: "Supine", page: 28, variations: [] },
      { name: "Chest Lift", category: "Abdominal", page: 30, variations: [] },
      { name: "Chest Lift with Rotation", category: "Abdominal", page: 31, variations: [] },
      { name: "The Hundred", category: "Abdominal", page: 32, variations: [] },
      { name: "The Roll Up", category: "Abdominal", page: 34, variations: [] },
      { name: "Neck Pull", category: "Abdominal", page: 37, variations: [], excluded: true },
      { name: "Rolling Like a Ball", category: "Abdominal", page: 39, variations: [] },
      { name: "Single Leg Stretch", category: "Abdominal", page: 42, variations: [] },
      { name: "Double Leg Stretch", category: "Abdominal", page: 43, variations: [] },
      { name: "Single Straight Leg Stretch", category: "Abdominal", page: 44, variations: [] },
      { name: "Double Straight Leg Stretch", category: "Abdominal", page: 45, variations: [] },
      { name: "Criss Cross", category: "Abdominal", page: 46, variations: [] },
      { name: "Teaser 1,2,3", category: "Abdominal", page: 47, variations: [] },
      { name: "Hip Circles", category: "Abdominal", page: 51, variations: [], excluded: true },
      { name: "어깨뼈와 어깨 관절의 움직임", category: "Side Lying", page: 54, variations: ["Telescope Arms (망원팔)", "Arm Opening", "Pinwheel (바람개비)"] },
      { name: "엉덩관절의 이완 및 근력 향상", category: "Side Lying", page: 57, variations: ["Thigh Stretch", "Clam Shell", "Side Bridge"] },
      { name: "Side Leg Lift Series", category: "Side Lying", page: 58, variations: ["Side Single Leg Lift", "Side Single Leg Circle", "Side Single Leg Front & Back Kick", "Side Single Leg Bicycle", "Side Single Lower Leg Lift", "Side Double Leg Lift"] }
    ]
  }
};
